### ISSUE TITLE
how

### ISSUE THREAD

**Issue by Quendic** [Samforquer/Dota2Project#7]
how can ı run this tool

**Comment by Samforquer** [comment]
Sure, first you'll need to clone the project to your machine, open the project in your IDE of choice, and run the spring boot application to start the backend server. 
Then you will need to start the frontend. In order to do this you will need to open a terminal window and navigate to the 'src/frontend' directory within the project,  and then run 'npm install' then 'npm run dev' to start the frontend, you should then be able to access the link
to: http://localhost:5173 to open it in a browser. 

I am currently working on deploying this tool to AWS for a much easier demo experience, and I will be sure to update the README in the meantime with more clear instructions for how to run it, thanks for bringing this to my attention, and let me know if this works for you!

**Comment by Samforquer** [comment]
I have just finished hosting this tool on AWS if you'd like to demo it without following all the above steps you can follow this link: http://mydota2heropickerappbucket.s3-website-us-east-1.amazonaws.com/
